[package]
name = "rldyourterm-interaction"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
crossterm.workspace = true
winit.workspace = true
tracing.workspace = true
rldyourterm-core.workspace = true
rldyourterm-services.workspace = true
rldyourterm-settings.workspace = true
