[package]
name = "rldyourterm-render-gpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
wgpu.workspace = true
rldyourterm-services = { path = "../../services" }
rldyourterm-foundation = { path = "../../foundation" }
rldyourterm-font = { path = "../font" }
tracing.workspace = true
bytemuck.workspace = true
pollster.workspace = true
