[package]
name = "rldyourterm-render-gpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
wgpu.workspace = true
rldyourterm-services.workspace = true
rldyourterm-font.workspace = true
tracing.workspace = true
bytemuck.workspace = true
pollster.workspace = true
