[package]
name = "rldyourterm-render-gpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
wgpu.workspace = true
rldyourterm-core = { path = "../../core" }
rldyourterm-foundation = { path = "../../foundation" }
tracing.workspace = true
font8x8.workspace = true
bytemuck.workspace = true
pollster.workspace = true
