[package]
name = "rldyourterm-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
crossterm.workspace = true
winit.workspace = true
softbuffer.workspace = true
rldyourterm-font.workspace = true
rldyourterm-ui.workspace = true
rldyourterm-foundation.workspace = true
rldyourterm-foundation-platform.workspace = true
rldyourterm-services.workspace = true
rldyourterm-render-cpu.workspace = true
rldyourterm-render-gpu.workspace = true
rldyourterm-settings.workspace = true
rldyourterm-shell-integration.workspace = true
rldyourterm-diagnostics.workspace = true
image.workspace = true
