[package]
name = "rldyourterm-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
crossterm.workspace = true
winit.workspace = true
softbuffer.workspace = true
rldyourterm-font = { path = "../features/font" }
rldyourterm-ui = { path = "../ui" }
rldyourterm-foundation = { path = "../foundation" }
rldyourterm-foundation-platform = { path = "../foundation-platform" }
rldyourterm-services = { path = "../services" }
rldyourterm-render-cpu = { path = "../features/render_cpu" }
rldyourterm-render-gpu = { path = "../features/render_gpu" }
rldyourterm-settings = { path = "../features/settings" }
rldyourterm-shell-integration = { path = "../features/shell_integration" }
rldyourterm-core = { path = "../core" }
rldyourterm-diagnostics = { path = "../features/diagnostics" }
image.workspace = true
