[package]
name = "rldyourterm-foundation-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
portable-pty.workspace = true
winit.workspace = true
arboard.workspace = true
tracing.workspace = true
rldyourterm-foundation.workspace = true
