[package]
name = "rldyourterm-services"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
rldyourterm-core.workspace = true
rldyourterm-foundation.workspace = true
